### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by NyxKazuya** [Jeff53978/Python-Trojan#1]
because it weighs too much in the scan photo it only weighs 15mb, and you shouldn't upload it to virustotal it burns all your work.
https://i.imgur.com/rrsZT56.png
oh and about startup, it doesn't work it would be great to add some persistence and start from any reboot or also adding it as a schedule task

**Comment by Jeff53978** [comment]
I will look into it

**Comment by AdamxzV3** [comment]
so does the rat works. since i want to try it on startup

**Comment by AdamxzV3** [comment]
and if its on startup, will be the rat deleted soon by an win antivirus?

**Comment by Jeff53978** [comment]
The rat is not detectable by windows antivirus as of this moment
